### ISSUE TITLE
Pārtaisīt visu bez `panic(err)`

### ISSUE THREAD

**Issue by briiC** [inflacijs/wiki-page#1]
pārraksti visu lai nav `panic(err)`
funkcijai jāatgriež tā:
```go
func dbConnection() (*sql.DB, error) {
```

un tur kur tu izsauc `dbConnection`. Tur tev jāpārbauda `err` un jātais `log`:
```go
db, err := dbConnection(); err != nil {
    log.Fatalf("Error: DB Connection: %s", err)
    return // ja tas ir main.go failā
}
```

Vislabāk būtu, ja tas būtu main failā, jo tur jāredz galvenās lietas, kas notiek. Kā piemēŗs:
```go
// pseido kods
func main() {
    cfg, err := LoadConfig("config.yml")
    if err != nil {
        log.Fatalf("Error: Config: %s", err)
        return
    }

    db, err := ConnectToDatabase(cfg) // redzi te cfg tiek padots, lai sasaistītu
   // var arī `cfg.ConnectToDatabase()`
    if err != nil {
        log.Fatalf("Error: Database: %s", err)
        return
    }

    // Handlers ..
   
    // Run server

}
```

**Comment by briiC** [comment]
Būtībā *visur*, kur funkcija atgriež err, tur jāņem tas vērā/jāapstrādā. Nedrīkst tā darīt
```go
 db, _ := dbConnection() // returns also error
```

**Comment by inflacijs** [comment]
Nesaprotu kaa man padot db taalaak uz Page.go faila funkcijaam save() un load().

**Comment by briiC** [comment]
vari sataisīt globālu mainīgo, kas būs pieejams visās funkcijāš. Tas nav forši, bet pagaidām vari

```go
package main

// DB tagad var lietot jebkurā funkcijā
var DB *sql.Database

func main() {
    DB, err = dbConnection()
   if err != nil {
   ....
}


}

**Comment by inflacijs** [comment]
Sapratu, tagad viss izdevās. Bet ilgtermiņā tas tad nav labi - turēt šādu globālu mainīgo ja ?

**Comment by briiC** [comment]
es tieši ar DB turu globālu dažos projektos. BEt kopumā labāk pa funkcijām dot
